import { defineField, defineType } from "sanity";
import { UserIcon } from "lucide-react";

export const Playlist = defineType( 
    {
        name: 'playList',
        title: 'playlist',
        type: 'document',
        icon: UserIcon,
        fields: [
            defineField({
                name: 'title',
                type:'string'
            }),
            defineField({   //auto generated by sanity based on option
                name: 'slug',
                type:'slug',
                options: {
                    source:'title'   
                }
            }),
            defineField({
                name: 'select',
                type:'array',
                of:[{type:'reference', to :[ {type:'startup'}]}]
            }),
           
        ],
    }
)