import { defineField, defineType } from "sanity";
import { UserIcon } from "lucide-react";

export const startup = defineType( 
    {
        name: 'startup',
        title: 'Startup',
        type: 'document',
        icon: UserIcon,
        fields: [
            defineField({
                name: 'title',
                type:'string'
            }),
            defineField({   //auto generated by sanity based on option
                name: 'slug',
                type:'slug',
                options: {
                    source:'title'   
                }
            }),
            defineField({
                name: 'author',
                type:'reference',
                to:{type:'author'}
            }),
            defineField({
                name: 'views',
                type:'number'
            }),
            defineField({
                name: 'decryption',
                type:'text'
            }),
            defineField({
                name: 'category',
                type:'string',
                validation: (Rule) => Rule.min(1).max(20).required().error("please enter a valid category"),
            }),
            defineField({
                name: 'image',  //we are not using sanity image upload feature
                type:'url',
                validation:(Rule) => Rule.required()
            }),
            defineField({
                name: 'pitch',
                type:'markdown'
            }),
        ],
    }
)